apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keylzasecsdevbxuks1
spec:
  provider: azure
  secretObjects:
  - secretName: nginx-cert
    type: kubernetes.io/tls
    data:
    - objectName: Web1AksSSL
      key: tls.key
    - objectName: Web1AksSSL
      key: tls.crt
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "MID_ID"
    keyvaultName: "keylzasecsdevbxuks1"         
    objects:  |
      array:
        - |
          objectName: Web1AksSSL
          objectType: secret        
    tenantId: "TENANT_ID"

